### ISSUE TITLE
Input sample rate

### ISSUE THREAD

**Issue by aswinp17** [wizardyesterday/HackRfDiags#1]
Hai i would like to know the input sampling rates supported by WbFMdemodulator. I used an IQ file dump from a fm tuner and it is not properly working in the WbFmDemodulator test app my IQ sample rate is 1024k samples/s also IQ data is 16 bit.

**Comment by wizardyesterday** [comment]
Heya,

I have the sample rate of the HackRF at 2.048x10^6 Samples/second.  For the
wideband FM demodulator I decimate down to 256000 Samples/second.

Now, the final output sample rate for the PCM data is 8000 Samples/second.

In the system design directory, I have pdf files that indicate the sample
rates of the demodulators. What I had not yet included in the system design
for the HackRF was the cascade of half-band filter decimators that decimate
the sample rate from 2.048x10^6 Samples/second down to 256000
Samples/second.

One might ask, why do I work with 256000S/s? Well it is an integer multiple
of 8000S/s (for the PCM data). That way I could avoid using rate changes of
L/M (I like integers).  What had happened was I first created my radio
diags for the rtlsdr, and when I got a HackRF, I ported my software to the
HackRF.  Other than performing integer math for the filters, I used the
same sample rates as the demodulators of the rtlsdr, and merely prescaled
everything to avoid redesigning the demodulator filters.

Note also that I provided live transmit functionality for the HackRF also.
In this case I run the modulators at 8000S/s (hardly ideal) and interpolate
the baseband data up to 2.048x10^6 S/s.

I know this was a long answer, and I hope that this helps.

Oh also, since both the HackRF and the rtlsdr use 8-bit data, the IQ data
format is 8 bit.  Note also that the rtlsdr uses offset binary format for
the IQ data, whereas, the HackRF uses 2's complement (signed) 8-bit IQ data.

Best regards,
Chris G.

**Comment by aswinp17** [comment]
Thank you for your quick reply i resampled my IQ to 2048k S/s now have to change my data format to 8 bit since my tuner only outputs 16 bit data.

**Comment by aswinp17** [comment]
hai how can i increase the output sampling  rate from 8000 to 6000S/s. what all changes should i make?

**Comment by wizardyesterday** [comment]
Hi,

I would modify the createPcmData() function so that the last stage of
decimation is not performed. You will probably have sime aliasing due to
the fact that the filter for the final filter cleans up any artifacts.  For
example, the filtet for the 16kHz sample rate curs off at 12kHz to ease the
transition region. This is standard in multirare design.

Best regards,
Chris G.

**Comment by aswinp17** [comment]
Thanks Chris ... I got it working . Used a resampler to up sample the audio out to the required sampling rate. . :)

**Comment by wizardyesterday** [comment]
You're very welcome Aswin! I'm glad that you got it working.

Best regards,
Chris G.

**Comment by wizardyesterday** [comment]
Hi Aswin,

The input sample rate is 8000 S/s. The modulators operate at that same
rate.  Once the signal is modulated at baseband, it is interpolated (in
several stages) to 2.048 x 10^6 S/s.

Best regards,
Chris G.
